// <auto-generated />
namespace UdemyVideoSite.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class PhonePropertyforAccounts : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(PhonePropertyforAccounts));
        
        string IMigrationMetadata.Id
        {
            get { return "202012160425313_PhonePropertyforAccounts"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
